[project]
name = "mcp-client-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "anyio>=4.11.0",
    "fastapi>=0.118.3",
    "fastembed-gpu>=0.7.3",
    "hf-xet>=1.2.0",
    "httpx>=0.28.1",
    "httpx-sse>=0.4.2",
    "jinja2>=3.1.6",
    "jsonschema>=4.25.1",
    "mcp-ui-server>=0.1.0",
    "mcp[cli]>=1.16.0",
    "onnxruntime-directml>=1.23.0",
    "openpyxl>=3.1.0",
    "pandas>=2.2.0",
    "pydantic>=2.12.0",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "qdrant-client[fastembed-gpu]>=1.15.1",
    "requests>=2.32.5",
    "uvicorn>=0.37.0",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "mcp>=1.16.0",
]
