"""
Real Workflow: Fetch Next.js docs and save locally

This workflow:
1. Queries context7 for Next.js API routes documentation
2. Queries context7 for React hooks documentation  
3. Combines both into a single markdown file
4. Saves to output/combined_docs.md
"""
import mcp

async def main():
    print("=== Starting Documentation Workflow ===")
    
    # Step 1: Get Next.js API routes documentation
    print("\n[1/4] Fetching Next.js API routes docs...")
    nextjs_docs = await mcp.use(
        "context7.query-docs",
        libraryId="/vercel/next.js",
        query="how to create API routes"
    )
    print(f"Got {len(str(nextjs_docs))} chars of Next.js docs")
    
    # Step 2: Get React hooks documentation
    print("\n[2/4] Fetching React hooks docs...")
    react_docs = await mcp.use(
        "context7.query-docs", 
        libraryId="/facebook/react",
        query="useEffect hook examples"
    )
    print(f"Got {len(str(react_docs))} chars of React docs")
    
    # Step 3: Create output directory
    print("\n[3/4] Creating output directory...")
    await mcp.use("filesystem.create_directory", path="output")
    
    # Step 4: Combine and save
    print("\n[4/4] Saving combined documentation...")
    combined_content = f"""# Combined Documentation

Generated by Governed Code Mode Workflow

---

## Next.js API Routes

{nextjs_docs}

---

## React useEffect Hook

{react_docs}

---

*Generated automatically*
"""
    
    await mcp.use(
        "filesystem.write_file",
        path="output/combined_docs.md",
        content=combined_content
    )
    
    print("\n=== Workflow Complete ===")
    print("Output saved to: output/combined_docs.md")
    
    return {
        "status": "success",
        "nextjs_docs_length": len(str(nextjs_docs)),
        "react_docs_length": len(str(react_docs)),
        "output_file": "output/combined_docs.md"
    }
