"""
Skill Injector for Sandbox - Layer 2 Abstraction.

Architecture:
  tools/      <- Layer 1: Raw MCP tools (generated by list_tools.py)
  skills/     <- Layer 2: Composed tasks using tools (this module loads)
  workflows/  <- Layer 3: Business logic using skills (created by agent)

Skills are ONLY loaded from the skills/ folder if they have a lib.py.
NO virtual skills - if you want a skill, create it explicitly.

Workflow mode only sees skills, not raw tools.
Skill creation mode sees tools from tools/ folder.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Callable, Awaitable, Dict, List, Optional

from .bindings import BindingProxy

log = logging.getLogger("sandbox.skill_injector")


class SkillModule:
    """
    A namespace object that holds skill functions.
    
    This is what gets injected as `skills.filesystem`, `skills.xlsx`, etc.
    """
    
    def __init__(self, name: str):
        self._name = name
    
    def __repr__(self) -> str:
        return f"<SkillModule:{self._name}>"


class SkillsNamespace:
    """
    The top-level `skills` namespace that holds all skill modules.
    
    This allows: `from skills import filesystem` or `skills.filesystem.read_file()`
    """
    
    def __init__(self):
        self._modules: Dict[str, SkillModule] = {}
    
    def __getattr__(self, name: str) -> SkillModule:
        if name.startswith('_'):
            raise AttributeError(name)
        if name not in self._modules:
            raise AttributeError(f"No skill module named '{name}'")
        return self._modules[name]
    
    def _register(self, name: str, module: SkillModule):
        self._modules[name] = module
    
    def __repr__(self) -> str:
        return f"<SkillsNamespace: {list(self._modules.keys())}>"


def load_skill_module(
    skill_name: str,
    binding: BindingProxy,
    lib_path: Path
) -> Optional[SkillModule]:
    """
    Load a skill module from its lib.py file.
    
    Skills are explicit - you must have a lib.py with functions.
    The binding proxy is injected as `_binding` for I/O operations.
    
    Args:
        skill_name: Name of the skill (e.g., "filesystem", "xlsx")
        binding: The BindingProxy for this skill's server
        lib_path: Path to lib.py file
    
    Returns:
        A SkillModule with the skill functions, or None if loading fails
    """
    if not lib_path.exists():
        log.debug(f"No lib.py for skill '{skill_name}'")
        return None
    
    try:
        code = lib_path.read_text(encoding='utf-8')
    except Exception as e:
        log.error(f"Failed to read {lib_path}: {e}")
        return None
    
    # Create execution environment with binding + standard libs
    import io
    import base64
    
    module_globals: Dict[str, Any] = {
        "_binding": binding,  # Inject the binding proxy
        "__name__": f"skills.{skill_name}",
        "__doc__": f"Skill module: {skill_name}",
        # Safe standard library modules
        "io": io,
        "base64": base64,
        # Type hint helpers
        "List": list,
        "Dict": dict,
        "Optional": type(None),
        "Any": object,
    }
    
    # Inject pandas for skills that need it (like xlsx)
    try:
        import pandas as pd
        module_globals["pd"] = pd
        module_globals["pandas"] = pd
    except ImportError:
        pass
    
    try:
        exec(code, module_globals)
    except Exception as e:
        log.error(f"Failed to execute {lib_path}: {e}")
        return None
    
    # Create the skill module and copy functions
    skill_module = SkillModule(skill_name)
    
    skip_keys = {'List', 'Dict', 'Optional', 'Any', 'io', 'base64', 'pd', 'pandas'}
    func_count = 0
    
    for key, value in module_globals.items():
        if key.startswith('_'):
            continue
        if key in skip_keys:
            continue
        if callable(value):
            setattr(skill_module, key, value)
            func_count += 1
    
    log.info(f"Loaded skill: {skill_name} ({func_count} functions)")
    return skill_module


def load_skill_modules(
    skills_dir: Path,
    bindings: Dict[str, BindingProxy]
) -> SkillsNamespace:
    """
    Load all skill modules from the skills/ directory.
    
    ONLY loads skills with a lib.py file.
    NO virtual/auto-generated skills.
    
    Args:
        skills_dir: Path to the skills directory
        bindings: Dict mapping server names to BindingProxy objects
    
    Returns:
        A SkillsNamespace with all loaded skill modules
    """
    # Map skill names to their primary binding server
    # Skills that don't have their own MCP server use another server's binding
    SKILL_BINDING_MAP = {
        "xlsx": "filesystem",  # xlsx skill uses filesystem for I/O
        "csv": "filesystem",   # csv skill would use filesystem
        "json": "filesystem",  # json skill would use filesystem
    }
    
    skills = SkillsNamespace()
    
    if not skills_dir.exists():
        log.warning(f"Skills directory not found: {skills_dir}")
        return skills
    
    for skill_folder in skills_dir.iterdir():
        if not skill_folder.is_dir():
            continue
        
        skill_name = skill_folder.name
        lib_path = skill_folder / "lib.py"
        
        # Only load if lib.py exists
        if not lib_path.exists():
            log.debug(f"Skipping '{skill_name}': no lib.py")
            continue
        
        # Get the binding for this skill
        binding_name = SKILL_BINDING_MAP.get(skill_name, skill_name)
        binding = bindings.get(binding_name)
        
        if not binding:
            log.warning(f"No binding '{binding_name}' for skill '{skill_name}'")
            continue
        
        skill_module = load_skill_module(skill_name, binding, lib_path)
        if skill_module:
            skills._register(skill_name, skill_module)
    
    log.info(f"Loaded {len(skills._modules)} skills: {list(skills._modules.keys())}")
    return skills


def create_import_handler(skills: SkillsNamespace) -> Callable:
    """
    Create a custom __import__ function that handles 'from skills import X'.
    
    This is injected into the sandbox's restricted builtins to allow
    skill imports while blocking all other imports.
    """
    def skill_import(name: str, globals_=None, locals_=None, fromlist=(), level=0):
        if name == 'skills' or name.startswith('skills.'):
            if name == 'skills':
                return skills
            else:
                parts = name.split('.')
                if len(parts) == 2:
                    skill_name = parts[1]
                    if hasattr(skills, skill_name):
                        return getattr(skills, skill_name)
                raise ImportError(f"No skill module named '{name}'")
        
        raise ImportError(f"Import not allowed in sandbox: {name}")
    
    return skill_import


# --- Test ---
if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    
    class MockBinding:
        async def list_directory(self, path):
            return [{"name": "test.py", "type": "file"}]
    
    mock_bindings = {"filesystem": MockBinding()}
    
    skills_dir = Path(__file__).parent.parent.parent / "skills"
    print(f"Loading skills from: {skills_dir}")
    
    skills = load_skill_modules(skills_dir, mock_bindings)
    print(f"Skills namespace: {skills}")
